services:
  mysql:
    image: mysql:latest
    container_name: mysql_app
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWD
      MYSQL_DATABASE: DB
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
